### ISSUE TITLE
RFE: Intent handling for VPN automation

### ISSUE THREAD

**Issue by michaelwingender** [vmlinz/strongswan-android-app#4]
Hi,
i hope this is the right place for some feature requests to the strongswan VPN Client app for Android. Yesterday I found out that you can handle Android Intents with Llama and Strongswan by using the action org.strongswan.android.action.START_PROFILE with the extra org.strongswan.android.VPN_PROFILE_ID (as long with the ID). I would like to have three features to seamlessly intergrate with apps that integrate Intents.
1. Usage of the extra with VPN profile ID as string instead of long. The extra data should be the profile name as you can see it within the app. This rfe is more a cosmetic rfe.
2. Instead of opening the app when fireing the Intent it should just start the VPN in the background.
3. Stop an VPN via Intent. I would like to add an Intent to Llama like org.strongswan.android.action.STOP_VPN to have the session ended when fireing the Intent.

To explain a little what I want to do: When I leave my home I would like to start the VPN connection to my Raspberry to have access to some applications like Asterisk. Whem I come home again the VPN is not necessary any more cause I can connect directly.

Thanks and br
Michael

**Comment by vmlinz** [comment]
@michaelwingender Thanks for reaching me. I'll try to update the codebase to latest official in weeks. You can reach the official devs for feature request or wait for my customized version of strongswan android. 

PS: official repo: https://github.com/strongswan/strongswan

Thanks.

**Comment by michaelwingender** [comment]
Thanks for your answer. So should I open an RFE in the official repo to have this features in the Play Store version of the official app? Or will you commit somehow?

**Comment by vmlinz** [comment]
Hi, at this time, you'd better ask for feature at the official play
comments. I now have not enough time to update the customized version.

Thanks for contacting.

**Comment by michaelwingender** [comment]
OK. Thanks. I hope somebody will be reading my comment in Play store. :-)
